import type { Metadata } from "next";
import { Inter,Epilogue,Poppins } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });
const epilogue = Epilogue({subsets:["latin"],
variable: '--font-epilogue',})
const poppins = Poppins({
  subsets: ["latin"],
  weight: "900", 
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
        <html lang="en">
      <body className={`${poppins.variable} ${epilogue.variable}`}>{children}</body>
    </html>
    </ReduxProvider>
    
  );
}

